/* Generated By:JavaCC: Do not edit this line. TsurgeonParserTreeConstants.java Version 6.0_1 */


namespace Edu.Stanford.Nlp.Trees.Tregex.Tsurgeon
{
	public interface ITsurgeonParserTreeConstants
	{
	}

	public static class TsurgeonParserTreeConstantsConstants
	{
		public const int Jjtroot = 0;

		public const int Jjtoperation = 1;

		public const int Jjtlocation = 2;

		public const int Jjtnodeselectionlist = 3;

		public const int Jjtnodeselection = 4;

		public const int Jjtnodename = 5;

		public const int Jjttreelist = 6;

		public const int Jjttreeroot = 7;

		public const int Jjttreenode = 8;

		public const int Jjttreedtrs = 9;

		public const string[] jjtNodeName = new string[] { "Root", "Operation", "Location", "NodeSelectionList", "NodeSelection", "NodeName", "TreeList", "TreeRoot", "TreeNode", "TreeDtrs" };
	}
}
