/* Generated By:JavaCC: Do not edit this line. SemgrexParserConstants.java */
using Sharpen;

namespace Edu.Stanford.Nlp.Semgraph.Semgrex
{
	/// <summary>Token literal values and constants.</summary>
	/// <remarks>
	/// Token literal values and constants.
	/// Generated by org.javacc.parser.OtherFilesGen#start()
	/// </remarks>
	internal interface ISemgrexParserConstants
	{
	}

	internal static class SemgrexParserConstantsConstants
	{
		/// <summary>End of File.</summary>
		public const int Eof = 0;

		/// <summary>RegularExpression Id.</summary>
		public const int Relation = 4;

		/// <summary>RegularExpression Id.</summary>
		public const int Alignreln = 5;

		/// <summary>RegularExpression Id.</summary>
		public const int Identifier = 6;

		/// <summary>RegularExpression Id.</summary>
		public const int Number = 7;

		/// <summary>RegularExpression Id.</summary>
		public const int Empty = 8;

		/// <summary>RegularExpression Id.</summary>
		public const int Root = 9;

		/// <summary>RegularExpression Id.</summary>
		public const int Regex = 10;

		/// <summary>Lexical state.</summary>
		public const int Default = 0;

		/// <summary>Literal token values.</summary>
		public const string[] tokenImage = new string[] { "<EOF>", "\" \"", "\"\\r\"", "\"\\t\"", "<RELATION>", "\"@\"", "<IDENTIFIER>", "<NUMBER>", "\"#\"", "\"$\"", "<REGEX>", "\"\\n\"", "\":\"", "\"(\"", "\")\"", "\"|\"", "\"&\"", "\"!\"", "\"?\""
			, "\"[\"", "\"]\"", "\",\"", "\"=\"", "\"{\"", "\";\"", "\"}\"" };
	}
}
