/* Generated By:JavaCC: Do not edit this line. TokenSequenceParserConstants.java */
using Sharpen;

namespace Edu.Stanford.Nlp.Ling.Tokensregex.Parser
{
	/// <summary>Token literal values and constants.</summary>
	/// <remarks>
	/// Token literal values and constants.
	/// Generated by org.javacc.parser.OtherFilesGen#start()
	/// </remarks>
	internal interface ITokenSequenceParserConstants
	{
	}

	internal static class TokenSequenceParserConstantsConstants
	{
		/// <summary>End of File.</summary>
		public const int Eof = 0;

		/// <summary>RegularExpression Id.</summary>
		public const int Identifier = 7;

		/// <summary>RegularExpression Id.</summary>
		public const int Regexvar = 8;

		/// <summary>RegularExpression Id.</summary>
		public const int Regexgroup = 9;

		/// <summary>RegularExpression Id.</summary>
		public const int Regexmrvar = 10;

		/// <summary>RegularExpression Id.</summary>
		public const int Regexmrgroup = 11;

		/// <summary>RegularExpression Id.</summary>
		public const int Backref = 12;

		/// <summary>RegularExpression Id.</summary>
		public const int Nonnegint = 13;

		/// <summary>RegularExpression Id.</summary>
		public const int Int = 14;

		/// <summary>RegularExpression Id.</summary>
		public const int Longint = 15;

		/// <summary>RegularExpression Id.</summary>
		public const int Real = 16;

		/// <summary>RegularExpression Id.</summary>
		public const int Regex = 17;

		/// <summary>RegularExpression Id.</summary>
		public const int Str = 18;

		/// <summary>RegularExpression Id.</summary>
		public const int Numcmp = 19;

		/// <summary>RegularExpression Id.</summary>
		public const int Strregexcmp = 20;

		/// <summary>RegularExpression Id.</summary>
		public const int Strsimple = 21;

		/// <summary>Lexical state.</summary>
		public const int Default = 0;

		/// <summary>Literal token values.</summary>
		public const string[] tokenImage = new string[] { "<EOF>", "\" \"", "\"\\r\"", "\"\\n\"", "\"\\t\"", "<token of kind 5>", "<token of kind 6>", "<IDENTIFIER>", "<REGEXVAR>", "<REGEXGROUP>", "<REGEXMRVAR>", "<REGEXMRGROUP>", "<BACKREF>", "<NONNEGINT>"
			, "<INT>", "<LONGINT>", "<REAL>", "<REGEX>", "<STR>", "<NUMCMP>", "<STRREGEXCMP>", "<STRSIMPLE>", "\"{\"", "\"=>\"", "\"}\"", "\"(\"", "\")\"", "\"tokens:\"", "\"text:\"", "\"=\"", "\";\"", "\"[\"", "\"]\"", "\",\"", "\":\"", "\".\"", "\"&&\""
			, "\"||\"", "\":case\"", "\":else\"", "\"^\"", "\"$\"", "\"*\"", "\"?\"", "\"+\"", "\"|\"", "\"&\"", "\"?:\"", "\"!\"", "\"{{\"", "\"}}\"", "\"::\"", "\"(?m)\"", "\"==>\"", "\"&annotate\"" };
	}
}
